kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-svc-role
  namespace: container
rules:
  - apiGroups: ['']
    resources: ['services']
    verbs: ['create']
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-svc-dist-role
  namespace: dist
rules:
  - apiGroups: ['']
    resources: ['services']
    verbs: ['create']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-svc-role-binding
  namespace: container
subjects:
  - kind: ServiceAccount
    name: fn-create-svc
    namespace: openfaas
roleRef:
  kind: Role
  name: fn-create-svc-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-svc-dist-role-binding
  namespace: dist
subjects:
  - kind: ServiceAccount
    name: fn-create-svc
    namespace: openfaas
roleRef:
  kind: Role
  name: fn-create-svc-dist-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fn-create-svc
  namespace: openfaas
  labels:
    app: openfaas
