kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-container-warnings-role
  namespace: container
rules:
  - apiGroups: ['']
    resources: ['events']
    verbs: ['list']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list']
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-container-warnings-dist-role
  namespace: dist
rules:
  - apiGroups: ['']
    resources: ['events']
    verbs: ['list']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-container-warnings-role-binding
  namespace: container
subjects:
  - kind: ServiceAccount
    name: fn-container-warnings
    namespace: openfaas
roleRef:
  kind: Role
  name: fn-container-warnings-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-container-warnings-dist-role-binding
  namespace: dist
subjects:
  - kind: ServiceAccount
    name: fn-container-warnings
    namespace: openfaas
roleRef:
  kind: Role
  name: fn-container-warnings-dist-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fn-container-warnings
  namespace: openfaas
  labels:
    app: openfaas
