kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-virtualsvc-role
  namespace: container
rules:
  - apiGroups: ['networking.istio.io']
    resources: ['virtualservices']
    verbs: ['create']
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-virtualsvc-dist-role
  namespace: dist
rules:
  - apiGroups: ['networking.istio.io']
    resources: ['virtualservices']
    verbs: ['create']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-virtualsvc-role-binding
  namespace: container
subjects:
  - kind: ServiceAccount
    name: fn-create-virtualsvc
    namespace: openfaas
roleRef:
  kind: Role
  name: fn-create-virtualsvc-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-virtualsvc-dist-role-binding
  namespace: dist
subjects:
  - kind: ServiceAccount
    name: fn-create-virtualsvc
    namespace: openfaas
roleRef:
  kind: Role
  name: fn-create-virtualsvc-dist-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fn-create-virtualsvc
  namespace: openfaas
  labels:
    app: openfaas
