version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080/faas/
functions:
  delete-secret:
    lang: golang-middleware
    namespace: openfaas
    handler: ./function
    image: lukwil/delete-secret:latest
    build_args:
      GO111MODULE: on
    annotations:
      topic: nats-delete-secret
      com.openfaas.serviceaccount: fn-delete-secret
    environment:
      namespace_single: container
      namespace_dist: dist
