version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080/faas/
functions:
  create-statefulset:
    lang: golang-middleware
    namespace: openfaas
    handler: ./function
    image: lukwil/create-statefulset:latest
    build_args:
      GO111MODULE: on
    annotations:
      com.openfaas.serviceaccount: fn-create-statefulset
    environment:
      namespace: container
      graphql_url: http://hasura.hasura.svc.cluster.local/v1/graphql
      nats_url: nats://nats.openfaas:4222
      topic_create_svc: nats-create-svc
