kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-secret-role
  namespace: container
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-secret-dist-role
  namespace: dist
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-secret-role-binding
  namespace: container
subjects:
- kind: ServiceAccount
  name: fn-create-secret
  namespace: openfaas
roleRef:
  kind: Role
  name: fn-create-secret-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-create-secret-dist-role-binding
  namespace: dist
subjects:
- kind: ServiceAccount
  name: fn-create-secret
  namespace: openfaas
roleRef:
  kind: Role
  name: fn-create-secret-dist-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fn-create-secret
  namespace: openfaas
  labels:
    app: openfaas