version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080/faas/
functions:
  create-minio-user:
    lang: golang-middleware
    namespace: openfaas
    handler: ./function
    image: lukwil/create-minio-user:latest
    build_args:
      GO111MODULE: on
    annotations:
      topic: nats-create-minio-user
    environment:
      minio_url: 127.0.0.1:9000
      minio_access_key: AKIAIOSFODNN7EXAMPLE
      minio_secret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      nats_url: nats://nats.openfaas:4222
      topic_set_minio_policy: nats-set-minio-policy
      topic_create_secret: nats-create-secret
