version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080/faas/
functions:
  delete-mpi:
    lang: golang-middleware
    namespace: openfaas
    handler: ./function
    image: lukwil/delete-mpi:latest
    build_args:
      GO111MODULE: on
    annotations:
      topic: nats-delete-mpi
      com.openfaas.serviceaccount: fn-delete-mpi
    environment:
      namespace: dist
      graphql_url: http://hasura.hasura.svc.cluster.local/v1/graphql
