version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080/faas/
functions:
  delete-svc:
    lang: golang-middleware
    namespace: openfaas
    handler: ./function
    image: lukwil/delete-svc:latest
    build_args:
      GO111MODULE: on
    annotations:
      topic: nats-delete-svc
      com.openfaas.serviceaccount: fn-delete-svc
    environment:
      graphql_url: http://hasura.hasura.svc.cluster.local/v1/graphql
      nats_url: nats://nats.openfaas:4222
      namespace_single: container
      namespace_distributed: dist
      topic_delete_statefulset: nats-delete-statefulset
      topic_delete_mpi: nats-delete-mpi
