kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-delete-pvc-role
  namespace: container
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-delete-pvc-role-binding
  namespace: container
subjects:
- kind: ServiceAccount
  name: fn-delete-pvc
  namespace: openfaas
roleRef:
  kind: Role
  name: fn-delete-pvc-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fn-delete-pvc
  namespace: openfaas
  labels:
    app: openfaas