version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080/faas/
functions:
  delete-minio-bucket:
    lang: golang-middleware
    namespace: openfaas
    handler: ./function
    image: lukwil/delete-minio-bucket:latest
    build_args:
      GO111MODULE: on
    environment:
      minio_url: 127.0.0.1:9000
      minio_access_key: AKIAIOSFODNN7EXAMPLE
      minio_secret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      nats_url: nats://nats.openfaas:4222
      topic_delete_minio_policy: nats-delete-minio-policy
      topic_delete_secret: nats-delete-secret
      topic_delete_minio_user: nats-delete-minio-user
